= ドメイン名の終活 - i6n26
n0nakamura
v0.0.1: draft
:backend: xhtml5
:experimental:
:sectnums: 
:sectnumlevels: 2
:sectlinks: 
:toc: auto
:lang: ja
:tabsize: 2
:favicon: 01GSH7D013HQPGGT11GD277EN2.svg
:stylesheet: style_asciidoctor.css
:linkcss:
:copycss:
:copyright: Copyright © 2023 n0nakamura
:description: 
:keywords: ドメイン名, 終活

[WARNING]
====
include::01GX2YHTCNZB241VGP2K2NDZ6A.adoc[]
====

[quote,君子]
____
始め有るものは必ず終わり有り
____

というお言葉{empty}footnote:[link:https://kotobank.jp/word/%E5%A7%8B%E3%82%81%E6%9C%89%E3%82%8B%E3%82%82%E3%81%AE%E3%81%AF%E5%BF%85%E3%81%9A%E7%B5%82%E3%82%8F%E3%82%8A%E6%9C%89%E3%82%8A-601126[始め有るものは必ず終わり有り(ハジメアルモノハカナラズオワリアリ)とは？ 意味や使い方 - コトバンク] を見て君子の法言であることを知った．揚子法言みたいなお言葉集を参照すると文書の説得力が増すのでおすすめだ、とジュンク堂書店池袋本店の5階に置かれている本に書かれていた．こういったお言葉に対する私の関心度は低いが、人類の共通の経験を統制語彙のように一つの表記で表すことができるのは魅力的だと思う．]{empty}があるように、ドメイン名にも我々の人生にも終わりがある．これはドメイン名の最期まで責任を持って管理したい、という人によるお話だ．

== ドメイン名というペット

閲覧者の中にはペットと一緒に暮らしている人もいるかもしれない．不測の事態により飼い主が世話をすることができない状況に陥った時に備えて、負担付死因贈与契約を結んだり、ペット信託を利用する人もいるだろう．そうした人たちは、ペットの命を保証することの難しさをよく理解しているものと思われる．

さて、インターネットを利用するとドメイン名を見かける機会が頻繁にある．URLにはドメイン名が含まれていることが多く、「ググれ」というスラングを生み出した ``google.com`` は最もよく知られているだろう{empty}footnote:[link:https://www.similarweb.com/ja/top-websites/[トップウェブサイトランキング - 2月 2023に最も訪問数が多いサイト ｜ シミラーウェブ] でもgoogle.comがトップにある．このランキングでは平均滞在時間も書かれているが、どのようにして測定しているのだろうか．]．公に使われるこれらのドメイン名は、レジストラに登録を申請し、必要に応じて料金を納付することで初めて利用が可能になる{empty}footnote:[ドメイン名やDNSの管理に関わる団体はICANNやIANA、JPNICやベリサインなどのレジストリ、お名前.comやGandiなどのレジストラ、などなど沢山存在する．link:https://www.nic.ad.jp/ja/question/domain3.html[Q&A - ドメイン名の登録事業者について - JPNIC]]．更に、ドメイン名は買い切り型ではなく、更新を必要とする．この更新を行わないと、一定期間後に改めて販売されることとなる． ``circleksunkus.jp`` がお名前.comで競売に出された例が有名だ．この例では6,000万円で落札され、ドメイン名がもつ資産価値を示している．ここまで大規模な競売でなくても、アフェリエイトサイトやフィッシングサイトに利用するため、中古ドメインが購入されることがある．

ドメイン名を長めに更新する場合でも最長10年が限界だろう．我々の命は儚く、インターネットが滅びるよりドメイン名管理者が先に死ぬ．我々の死後にドメイン名を悪用されたとなっては、死んでも死にきれない．この点において、ペットとドメイン名が抱える問題構造は共通しているといえる．

== ドメイン名の行方の実際

なるほど、実際に破棄されたドメイン名はどうなっているか．

link:https://www.site-z.com/item.php?id=4[あなたの死後、サイトは消滅する！？ASP、ドメイン、サーバーの相続対策 - サイト売買Ｚ] ではウェブサイトの引継ぎについて、レンタルサーバ会社、レジストラ、ASPに問い合わせをおこなっている．

== ドメイン名の終活

では、管理できなくなるであろうドメインはどうすればよいのだろうか．例えばドメイン名の譲渡/相続が考えられる．ドメイン名は

しばしばドメイン名に自身を示す名称や特定の意味を示す文字列を採用する例が見られるが、これはドメイン名の引継人にとって再利用しづらい負債となる．

== まとめ
