= ドライアイに優しいパソコン環境 - i6n26
n0nakamura
v0.0.1: draft
:backend: xhtml5
:experimental:
:sectnums: 
:sectnumlevels: 2
:sectlinks: 
:toc: auto
:lang: ja
:tabsize: 2
:favicon: 01GSH7D013HQPGGT11GD277EN2.svg
:stylesheet: style_asciidoctor.css
:linkcss:
:copycss:
:copyright: Copyright © 2023 n0nakamura
:description: ドライアイに悩まされている筆者が、目を閉じながらも入力することのできると期待している漢字直接入力や、スクリーンリーダーに手を染める話．
:keywords: 漢字直接入力

[WARNING]
====
include::01GX2YHTCNZB241VGP2K2NDZ6A.adoc[]
====

== ドライアイが辛い

コンピュータの画面を見つめ続けることでドライアイになり、起床直後の目の乾きに特に苦しんでいた．画面に向き合う時間に相関していることは明らかであり、この時間を減らすことが根本的な解決策であると考え始めた．

== 漢字直接入力

=== 画面を見なくても入力できる方式を求めて

コンピュータに親しい人は、入力方式についてもこだわりを持っていることが多い．私もGoogle日本語入力/Mozcをカスタマイズして使用しており、Windows標準のMicrosoft IMEを触ると指が拒否反応を示す．かな漢字変換方式にある程度満足しており、SKKなど異なる入力方式に手を出したことはなかった．

「画面を見ずに変換することができる」という触れ込みをインターネットで見かけ、漢字直接入力に惹かれた．

== スクリーンリーダー

=== 画面を見なくてもインターネットブラウジングしたい

私は筑波技術大学に1年間在学していた．筑波技術大学は聴覚もしくは視覚に障害をもつことを入学条件にしている興味深い大学だ．当然視覚障害に対する設備も整っており、私は視覚障害者が通学する春日キャンパスでスクリーンリーダーを試す機会を頂いたことがあった．

しかし、これらはほとんどがMicrosoft製品/Apple製品上で動作するものである．私はLinuxを利用しており、Linuxで動作するスクリーンリーダーが欲しいのである．

=== Orcaを試す

LinuxにおけるスクリーンリーダーではOrcaが最も有名だろう．
