[#01J6VS8F7PHKH2651A52Q0WWWK]
= Webサイトを見直す
n0nakamura
v1.0.0: publish
:experimental:
:sectnums: 
:sectnumlevels: 2
:sectlinks: 
:toc: auto
:lang: ja
:tabsize: 2
:copyright: Copyright © 2024 n0nakamura
:firstdocdatetime: 2024-09-03T20:38:17+0900
:docdatetime: 2024-09-04T22:53:17+0900
:description: Webサイトを改善しようと思って数ヶ月が経過しているため、方針を見直す話。
:keywords: blog, web site

DocBookをベースとした独自スキーマで文書を書き換えたいとか思っているだけで、実際に行動に移せていなかったので、現状に沿ったブログシステムに切り替えて、少なくとも情報発信は継続できる状況にしたいね、という話です。

[#01J6VVQRTZ1566E4AEZPNBSG68]
== 経緯

情報発信したい気持ちがありつつも、「Webサイトのシステムをマシにしてから投稿しよう」という気持ちで、情報発信自体も先送りにしている現状がありました。このままだとGitHubやCloudflareの資源の無駄遣いでしかないので、現状の能力やパワーで手の届く範囲から改善を試みるという方向転換をしました。

[#01J6VVQX4REKRJ2MS4TCQ2NYM9]
== 解決方針

最も早急に解決すべき問題は、情報発信が滞っている事でした。まずは情報発信をしたいと思ったときにできるよう、Webサイトのシステムと、発信コンテンツの分離を行いました。これまでもWebサイトのシステムと発信コンテンツはGitで管理しており、Git Submodulesを用いることで両者を疎結合にすることで、次の2つのメリットを享受できました。

* Webサイトシステムをすげ替える場合でも、コンテンツに影響が及びにくい。
* コンテンツの変更履歴を維持しやすい。

[#01J6VVR197E48NSA0ZQRQ8TTJD]
== 全く関係ないあとがき

実はGPG鍵の失効期限が過ぎてGitの署名ができない状態が続いてました。これも情報発信をしない要因のひとつになっていたので、こういう、サンマの骨が刺さったかのような阻害要因と実行力のない完璧主義が組み合わさって動けなくなる人間を卒業したい。
